std = "selene-requires"
exclude = ["test/TestEZ/**"]

[config]
	empty_if = { comments_count = true }

[rules]
	# Too aggressive in tests
	unused_variable = "allow"
	# Handled by formatting/StyLua
	multiple_statements = "allow"
	# Used for Luau type assertions
	shadowing = "allow"
