[package]
	name = "znotfireman/hotfusion"
	description = "Fork of Fusion with improvements used by Team Fireworks"
	license = "MIT"
	authors = ["Elttob", "ImNotFireMan123"]
	version = "0.1.0"

	registry = "https://github.com/UpliftGames/wally-index"
	realm = "shared"

	exclude = ["**"]
	include = ["out", "out/*", "build.project.json", "wally.lock", "wally.toml"]

[dependencies]
